# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_sandbox/',
                'doc_host': 'https://manisnesan.github.io',
                'git_url': 'https://github.com/manisnesan/nbdev_sandbox/',
                'lib_path': 'nbdev_sandbox'},
  'syms': { 'nbdev_sandbox.api': {'nbdev_sandbox.api.sf_kcssearch': ('api.html#sf_kcssearch', 'nbdev_sandbox/api.py')},
            'nbdev_sandbox.core': { 'nbdev_sandbox.core.HelloSayer': ('core.html#hellosayer', 'nbdev_sandbox/core.py'),
                                    'nbdev_sandbox.core.HelloSayer.__init__': ('core.html#__init__', 'nbdev_sandbox/core.py'),
                                    'nbdev_sandbox.core.HelloSayer.say': ('core.html#say', 'nbdev_sandbox/core.py'),
                                    'nbdev_sandbox.core.foo': ('core.html#foo', 'nbdev_sandbox/core.py'),
                                    'nbdev_sandbox.core.say_hello': ('core.html#say_hello', 'nbdev_sandbox/core.py')},
            'nbdev_sandbox.exp_test': {'nbdev_sandbox.exp_test.addition': ('export_test.html#addition', 'nbdev_sandbox/exp_test.py')}}}