# AUTOGENERATED! DO NOT EDIT! File to edit: ../04_api.ipynb.

# %% auto 0
__all__ = ['sf_kcssearch']

# %% ../04_api.ipynb 7
import requests, json
def sf_kcssearch(query: str='540413'):
    url = "https://access.redhat.com/hydra/rest/search/v2/kcs"
    payload = json.dumps({"start": 0, "rows": 5,"q": f"{query}","expression": "fl=allTitle,id,score&fq=(documentKind: Solution) OR (documentKind: Article) OR (documentKind: Cve) OR (documentKind: Errata) OR (documentKind: LabInfo) OR (documentKind: Video) OR (documentKind: Vulnerability) OR (documentKind: CertifiedHardware) OR (documentKind: CertifiedSoftware) OR (documentKind: CertifiedCloudPartner)"})
    headers = {'Accept': 'application/json', 'Content-Type': 'application/json'}
    response = requests.request("POST", url, headers=headers, data=payload)
    return response.json()
